config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  root 'posts#index'
  get 'posts/followings'
  post 'posts/liked_users'
  post 'comments/switch'
  resources :posts, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
  end
  resources :comments, only: [:create]
  resources :users, only: [:show] do
    resources :user_relations, only: [:create, :destroy]
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  # 140文字で制限
  validates :content, length: {maximum: 140}

  # ユーザとの連携
  belongs_to :user
  # 投稿との連携
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  # コメント
  def create
    @comment = current_user.comments.new(comment_params)
    # Ajax呼び出しのみ有効
    respond_to do |format|
      if @comment.save
        NotificationMailer.send_comment(@comment).deliver_later
        format.js { render :create_success }
      else
        format.js { render :create_error }
      end
    end
  end

  # コメント表示切替
  def switch
    @post = Post.find(params[:post_id])
    # コメント表示かどうかをbool変換
    @open = ActiveModel::Type::Boolean.new.cast(params[:open])

    # Ajax呼び出しのみ有効
    respond_to do |format|
      format.js { render :switch }
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_button.html.haml
-# コメントボタン
= form_with url: comments_switch_path, remote: true do |f|
  = f.hidden_field :post_id, value: post.id, id: ''
  = f.hidden_field :open, value: !open, id: ''
  %button.btn.btn-outline-info.btn-sm{ type: 'submit', class: ('active' if open) }
    = open ? '▲コメント' : '▼コメント'
    -# コメント件数
    - if post.comments.count > 0
      %span.badge.badge-outline-info
        = post.comments.count

app/views/comments/_comment_count.html.haml
.btn.btn-outline-info.btn-sm.disabled
  = 'コメント'
  -# コメント件数
  - if post.comments.count > 0
    %span.badge.badge-outline-info
      = post.comments.count

app/views/comments/_comment_line.html.haml
-# 開いている時のみ
- if open
  -# コメントライン
  - post.comments.each do |comment|
    .alert.alert-info.border-info
      %span
        - if comment.user.present?
          -# ユーザ名
          %strong
            = link_to comment.user.user_name, user_path(comment.user_id)
          -# フォローボタン
          %span{class: "follow_button_#{comment.user_id}", style: "display:inline-flex"}
            = render 'user_relations/follow_button', user: comment.user
        = comment.created_at.strftime('%Y/%m/%d %H:%M')
      %pre{style: 'background-color: transparent;'}
        = comment.content
  -# コメント入力
  = form_with model: Comment.new, remote: true do |f|
    .field
      = f.hidden_field :post_id, value: post.id, id: ''
      = f.text_area :content, size: "50x2", class: 'form-control', id: ''
      = f.submit 'コメントする', class: 'btn btn-info'

app/views/comments/create_error.js.haml
-# トーストでコメント失敗通知
toastr.error("コメント登録 に失敗しました。");

app/views/comments/create_success.js.haml
-# コメント部分テンプレートを置き換える
$('.comment_button_#{@comment.post_id}').html("#{j render 'comments/comment_button', {post: @comment.post, open: true}}");
$('.comment_count_#{@comment.post_id}').html("#{j render 'comments/comment_count', {post: @comment.post}}");
$('.comment_line_#{@comment.post_id}').html("#{j render 'comments/comment_line', {post: @comment.post, open: true}}");
-# トーストでコメント成功通知
toastr.info("コメント しました。");

app/views/comments/switch.js.haml
-# コメント部分テンプレートを置き換える
$('.comment_button_#{@post.id}').html("#{j render 'comments/comment_button', {post: @post, open: @open}}");
$('.comment_count_#{@post_id}').html("#{j render 'comments/comment_count', {post: @post}}");
$('.comment_line_#{@post.id}').html("#{j render 'comments/comment_line', {post: @post, open: @open}}");