config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  root 'posts#index'
  get 'posts/followings'
  post 'posts/liked_users'
  post 'comments/switch'
  resources :posts, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
  end
  resources :comments, only: [:create]
  resources :users, only: [:show] do
    resources :user_relations, only: [:create, :destroy]
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  # ユーザ
  belongs_to :user
  # 投稿
  belongs_to :post

  # ユーザIDと投稿IDは必須
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  # いいね生成
  def create
    @post = Post.find(like_params[:post_id])
    @like = current_user.like_post(@post)
    # Ajax呼び出しのみ有効
    respond_to do |format|
      if @like.save
        format.js { render :create_success }
      else
        format.js { render :create_error }
      end
    end
  end

  # いいね解除
  def destroy
    @post = Post.find(like_params[:post_id])
    @like = current_user.unlike_post(@post)
    # Ajax呼び出しのみ有効
    respond_to do |format|
      if @like.destroy
        format.js { render :destory_success }
      else
        format.js { render :destory_error }
      end
    end
  end

  private
    def like_params
      params.require(:like).permit(:post_id)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_button.html.haml
-# いいねボタン
- if current_user.liking_post?(post)
  = form_with model: [post, current_user.likes.find_by(post_id: post.id)], method: :delete, remote: true do |f|
    = f.hidden_field :post_id, value: post.id, id: ''
    = f.submit 'いいね中', class: 'btn btn-primary btn-sm'
- else
  = form_with model: [post, current_user.likes.build], remote: true do |f|
    = f.hidden_field :post_id, value: post.id, id: ''
    = f.submit 'いいね', class: 'btn btn-outline-primary btn-sm'
-# いいね件数
- if post.likes.count > 0
  -# いいねユーザダイアログを開き、その際に投稿IDをいいねボタンフォームに設定
  %button.btn.badge.badge-outline-primary{ type: 'button', value: post.id, 'data-toggle': 'modal', 'data-target': '#likedUserDialog' }
    = post.likes.count

app/views/likes/_like_dialog.html.haml
= javascript_include_tag 'like_dialog'

-# いいねユーザダイアログ
.modal.fade#likedUserDialog{tabindex: -1, role: 'dialog', 'aria-labelledby': 'postDialogLabel', 'aria-hidden': 'true'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %h5.modal-title#likedUserDialogLabel
          いいね しているユーザー
        %button.close{type: 'button', 'data-dismiss': 'modal', 'aria-label': 'Close'}
          %span{'aria-hidden': 'true'}
            &times;
      .modal-body
        #likedUserDialogBody
      .modal-footer
        %button.btn.btn-secondary{type: 'button', 'data-dismiss': 'modal'}
          閉じる
-# いいねユーザ一覧取得フォーム
= form_with id: 'likedUsersForm', url: posts_liked_users_path, remote: true do |f|
  = f.hidden_field :id, id: ''
  = f.submit '', style: 'display: none'

app/views/likes/create_error.js.haml
-# トーストでいいね失敗通知
toastr.error("いいね に失敗しました。");

app/views/likes/create_success.js.haml
-# いいねボタン部分テンプレートを置き換える
$('.like_button_#{@like.post_id}').html("#{j render 'likes/like_button', post: @post}");
-# トーストでいいね成功通知
toastr.success("いいね しました。");

app/views/likes/destory_error.js.haml
-# トーストでフォロー解除失敗通知
toastr.error("いいね の解除に失敗しました。");

app/views/likes/destory_success.js.haml
-# いいねボタン部分テンプレートを置き換える
$('.like_button_#{@like.post_id}').html("#{j render 'likes/like_button', post: @post}");
-# トーストでフォロー解除成功通知
toastr.info("いいね を解除しました。");