config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  root 'posts#index'
  get 'posts/followings'
  post 'posts/liked_users'
  post 'comments/switch'
  resources :posts, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
  end
  resources :comments, only: [:create]
  resources :users, only: [:show] do
    resources :user_relations, only: [:create, :destroy]
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  # 140文字で制限
  validates :content, length: {maximum: 140}
  # 画像登録
  mount_uploader :picture, PictureUploader

  # ユーザと連携
  belongs_to :user
  # コメントとの連携
  has_many :comments

  # いいねテーブルとの連携
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  # 指定日のいいね数ランキングトップ10の投稿の {key: 投稿、val: [順位, カウンタ]} のハッシュを返す
  def self.ranking_hash(date)
    h_ranking = {}
    # いいね数ランキングトップ10の投稿ID:カウンタハッシュを取得
    h_like_count = Like.group(:post_id)
      .where('created_at >= ? AND created_at <= ?', date.beginning_of_day, date.end_of_day)
      .order('COUNT(post_id) DESC').limit(10).count(:post_id)
    # 投稿があればメール通知
    if h_like_count.size > 0
      # 同一順位を考慮
      current_no = 0
      current_like_count = 0
      # 投稿を一括取得(ランキング順にソート)してループ
      ids = h_like_count.keys
      Post.where(id: ids).sort_by{|p| ids.index(p.id)}.each.with_index(1) do |post, no|
        # いいね数を取得
        like_count = h_like_count[post.id]
        # 前データと同じなら順位を更新しない
        current_no = no if (current_like_count > like_count || current_like_count == 0)
        current_like_count = like_count
        # key: 投稿、val: [順位, カウンタ]
        h_ranking[post] = [current_no, current_like_count]
      end
    end
    h_ranking
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  # 全体タイムライン
  def index
    @posts = Post.includes(:user).page(params[:page]).per(10).order(created_at: "DESC")
  end

  # フォローしたユーザーのみのタイムライン
  def followings
    @posts = current_user.followings_posts.includes(:user).page(params[:page]).per(10).order(created_at: "DESC")
  end

  # 投稿表示
  def show
    @post = Post.find(params[:id])
  end

  # 投稿
  def create
    @post = current_user.posts.build(post_params)
    # Ajax呼び出しのみ有効
    respond_to do |format|
      if @post.save
        # 全体タイムラインなら遷移先指定
        @transition_url = referer_path_match_controller_action('posts', 'index')
        format.js { render :create_success }
      else
        format.js { render :create_error }
      end
    end
  end

  # いいねしているユーザ一覧部分テンプレート
  def liked_users
    @post = Post.find(params[:id])
    # Ajax呼び出しのみ有効
    respond_to do |format|
      format.js
    end
  end

  private
    def post_params
      params.require(:post).permit(:content, :picture)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_liked_users_part.html.haml
- post.liked_users.each do |user|
  %div
    -# ユーザ名
    %strong
      = link_to user.user_name, user_path(user.id)
    -# フォローボタン
    %span{class: "follow_button_#{user.id}", style: "display:inline-flex"}
      = render 'user_relations/follow_button', user: user

app/views/posts/_timeline.html.haml
= javascript_include_tag 'timeline'

-# 自動スクロール
.scroll-list.jscroll
  - @posts.each do |post|
    .alert.alert-primary.border-primary
      %span
        - if post.user.present?
          -# ユーザ名
          %strong
            = link_to post.user.user_name, user_path(post.user_id)
          -# フォローボタン
          %span{class: "follow_button_#{post.user_id}", style: "display:inline-flex"}
            = render 'user_relations/follow_button', user: post.user
        = link_to post.created_at.strftime('%Y/%m/%d %H:%M'), post_path(post.id)
      %pre.lead{style: 'background-color: transparent;'}
        = post.content
      - if post.picture.present?
        %div
          = link_to image_tag(post.picture.thumb.url), post_path(post.id), target: "_blank"
      -# いいねボタン
      %span{class: "like_button_#{post.id}", style: "display:inline-flex"}
        = render 'likes/like_button', post: post
      -# コメントボタン
      %span{class: "comment_button_#{post.id}", style: "display:inline-flex"}
        = render 'comments/comment_button', {post: post, open: false}
      -# コメントライン
      %div{class: "comment_line_#{post.id}"}
        = render 'comments/comment_line', {post: post, open: false}
  = paginate @posts

-# いいねダイアログ
= render 'likes/like_dialog'

app/views/posts/create_error.js.haml
-# エラーメッセージのクリア
$('#error_explanation ul').empty();
-# エラーメッセージを追加
$('#error_explanation h2').text('入力に #{pluralize(@post.errors.count, "件")} エラーがあります');
- @post.errors.full_messages.each do |post|
  $('#error_explanation ul').append('<li>#{post}</li>');
-# エラーメッセージを表示
$('#error_explanation').show();

app/views/posts/create_success.js.haml
-# モーダル非表示
$('#postDialog').modal('hide');
-# エラーメッセージの非表示
$('#error_explanation').hide();
-# URLがあれば遷移
- if @transition_url.present?
  window.location.href = "#{@transition_url}";

app/views/posts/followings.html.haml
%h3 フォローしたユーザのみのタイムライン
= render 'posts/timeline'

app/views/posts/index.html.haml
%h3 全体タイムライン
= render 'posts/timeline'

app/views/posts/liked_users.js.haml
-# いいねダイアログのユーザ一覧を更新する
$('#likedUserDialogBody').html("#{j render 'posts/liked_users_part', post: @post}");

app/views/posts/show.html.haml
.alert.alert-primary.border-primary
  %span
    - if @post.user.present?
      -# ユーザ名
      %strong
        = link_to @post.user.user_name, user_path(@post.user_id)
      -# フォローボタン
      %span{class: "follow_button_#{@post.user_id}", style: "display:inline-flex"}
        = render 'user_relations/follow_button', user: @post.user
    = @post.created_at.strftime('%Y/%m/%d %H:%M')
  -# 本文
  %pre.h1{style: 'background-color: transparent;'}
    = @post.content
  -# 画像
  - if @post.picture.present?
    %div
      = image_tag @post.picture.url
  -# いいねボタン
  %span{class: "like_button_#{@post.id}", style: "display:inline-flex"}
    = render 'likes/like_button', post: @post
  -# コメントカウント
  %span{class: "comment_count_#{@post.id}", style: "display:inline-flex"}
    = render 'comments/comment_count', {post: @post}
  -# コメントライン
  %div{class: "comment_line_#{@post.id}"}
    = render 'comments/comment_line', {post: @post, open: true}

-# いいねダイアログ
= render 'likes/like_dialog'